image: node:latest

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - yarn global add @angular/cli
    - yarn
    - yarn build:gitlab
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
