image: node:latest

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - yarn
    - yarn build --prod --sourcemap=false
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
